config/routes.rb
Rails.application.routes.draw do
  root 'employees#index'
  get 'employee_login', to: 'employees#employee_login'
  post 'create_login', to: 'employees#create_login'
  get  'employee_logout', to: 'employees#employee_logout'
  get 'new_query',to: 'user_queries#new_query'
  post 'add_query',to: 'user_queries#add_query'
  get 'display_query', to:'user_queries#display_query'
  get 'view_query', to:'user_queries#view_query'
  post 'save_reply', to: 'replies#save_reply'
  post 'save_owner', to: 'replies#save_owner'
  get 'onhold_status', to: 'replies#onhold_status'
  get 'view_reply', to: 'user_queries#view_reply'
  get 'view_details', to: 'user_queries#view_details'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord

end

app/models/reply.rb
class Reply < ApplicationRecord
end

app/models/user_query.rb
class UserQuery < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  def index
  end
  def employee_login
  
  end
  def create_login
  	puts ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
  	puts params.inspect
  if @employee=Employee.find_by(:email=>params[:employee][:email])
  	if @employee.password_hash==params[:employee][:password]
  		session[:e_id]=@employee.e_id
  		session[:e_name]=@employee.name
  		  	redirect_to display_query_path


  	else
  		flash[:faliure]="password error"
      redirect_to employee_login_path
  	end
   else
   	flash[:faliure]="employee with this name is not exists"
    redirect_to employee_login_path
  end

  end
  def employee_logout
  	session[:e_id]=nil
  	session[:e_name]=nil
  	redirect_to root_path

  end

end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController


def save_reply
	puts "ddddddddddddddddddddddddddddddddddddddddddd"
	puts  params.inspect
	@reply= Reply.new
	@reply.ticket_id=params[:reply][:ticket_id]
	@reply.reply=params[:reply][:reply]
	@reply.replied_by=session[:e_name]
	@reply.save
	@user_query=UserQuery.find_by(:ticket_id=>params[:reply][:ticket_id])
	@user_query.owner=session[:e_name]
	@user_query.status="completed"
	@user_query.save
	QueryMailer.query_replied(@user_query).deliver
    redirect_to display_query_path


end

def save_owner
    @user_query=UserQuery.find_by(:ticket_id=>params[:employee][:ticket_id])
	@user_query.owner=params[:owner]
	@user_query.status="waiting for the owner reply"
	@user_query.save
	QueryMailer.owner_assigned(@user_query).deliver
    redirect_to display_query_path
	
end

def onhold_status

    @user_query=UserQuery.find(params[:format])
    @user_query.owner=session[:e_name]
    @user_query.status="On Hold"
    @user_query.save
	QueryMailer.owner_assigned(@user_query).deliver
    redirect_to display_query_path


   
end
end

app/controllers/user_queries_controller.rb
class UserQueriesController < ApplicationController
def new_query
@user_query = UserQuery.new
end
def add_query
	if params[:user_query][:subject]==nil ||params[:user_query][:raised_by]==nil||params[:user_query][:query]==nil
		flash[:failure]="fill all necessary fields"
		redirect_to new_query_path
	else
	@user_query = UserQuery.new
	@user_query.subject=params[:user_query][:subject]
	@user_query.department=params[:department]
	@user_query.raised_by=params[:user_query][:raised_by]
	@user_query.email=params[:user_query][:email]
	@user_query.status="waiting for staff response"
	@user_query.query=params[:user_query][:query]
	extension=rand(100000)
	ticket_value="ABC-#{extension}"
	@user_query.ticket_id=ticket_value
	@user_query.save!
	QueryMailer.registration_confirmation(@user_query).deliver
	redirect_to root_path
    end


end

def display_query
	@unassigned=UserQuery.where("owner IS ?", nil)
	@assigned=UserQuery.where("status != ? AND owner = ?", "completed", session[:e_name])
	@completed=UserQuery.where("status = ? AND owner = ?", "completed", session[:e_name])

end

def view_query
	@user_query=UserQuery.find(params[:format])
	@employee=Employee.all
	
end
def view_reply
@user_query=UserQuery.find(params[:format])
@reply=Reply.find_by(:ticket_id=>@user_query.ticket_id)
end
def view_details 
@user_query=UserQuery.find(params[:format])
@reply=Reply.find_by(:ticket_id=>@user_query.ticket_id)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/user_queries_helper.rb
module UserQueriesHelper
end

app/views/employees/employee_login.html.erb
<%=form_for :employee, url: create_login_path,method: :post do |f| %>
  
<div class="center-container-login">
    <div class="well">
      <p>
        <%= f.label :email %><br>
        <%=f.text_field(:email, {:class=>'form-control'}) %>
      </p>
      
      <p>
        <%= f.label :password %><br><span>
        <%=f.password_field(:password, {:class=>'form-control'}) %></span>
      </p>
      <p>
        <%=f.submit "Log In" ,:class=>"btn btn-success" %>
      </p>
    </div>
    </div>
<%end%>

app/views/employees/index.html.erb
<h1>Home_page</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tech Coders</title>
    <%= javascript_include_tag :defaults %> 
        <%= javascript_include_tag :application %>
    <%= csrf_meta_tags %>
    <%=stylesheet_link_tag 'site' %>

    
            <%= stylesheet_link_tag   'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>

  </head>

  <body>
   <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
             </button>
              <a class="navbar-brand" href="#">Tech_Coders</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
             
              <%if session[:e_id]== nil%>
              
              <ul class="nav navbar-nav navbar-right">
                <li> <%=link_to "Ask A Query",new_query_path%></li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                <li> <%=link_to "Employee_login",employee_login_path%></li>
              </ul>
              <%else%>
              <ul class="nav navbar-nav navbar-right">
                <li> <%=link_to "Logout",employee_logout_path%></li>
              </ul>
              <%end%>
            </div><!--/.nav-collapse -->
        </div>
      </nav>
      <% flash.each do |a,b| %>
            <%if a=="success"%>
              <div class ="alert alert-default"><%= b%></div>
            <%else%>
              <div class ="alert alert-danger"><%= b%></div>
            <%end%>
          <%end%>
    <%= yield %>
    <style>body{
        padding-top:70px;
      }</style>
  </body>
</html>

app/views/user_queries/display_query.html.erb
<hr/>
<div class="tab">
  <button class="tablinks" id="defaultOpen" onclick="openList(event, 'Unassigned')">UnAssigned tokens</button>
  <button class="tablinks" onclick="openList(event, 'Assigned')">Assigned Tokens</button>
  <button class="tablinks" onclick="openList(event, 'Completed')">Completed</button>
</div>

<div id="Unassigned" class="tabcontent">
  <%if @unassigned%>
  <%@unassigned.each do |unassigned|%>
  <div class="ticket-div">
  <h4><%=unassigned.subject%></h4>
    <h6 class="div-dep-ticket">Department : <%=unassigned.department%></h6>
    <div class="float-right"><%=link_to "View",view_query_path(unassigned)%></div>
  </div>
  <%end%>
  <%end%>
</div>

<div id="Assigned" class="tabcontent">
<% if @assigned%>
 <%@assigned.each do |assigned|%>
  <div class="ticket-div">
  <h4><%=assigned.subject%></h4>
    <h6 class="div-dep-ticket">Department : <%=assigned.department%></h6>
    <h6 class="div-dep-ticket">Owner: <%=assigned.owner%></h6>
    <div class="float-right"><%=link_to "View",view_query_path(assigned)%></div>
  </div>
  <%end%>
  <% end%>
</div>

<div id="Completed" class="tabcontent">
 <% if @completed%>
 <%@completed.each do |completed|%>
  <div class="ticket-div">
  <h4><%=completed.subject%></h4>
    <h6 class="div-dep-ticket">Department : <%=completed.department%></h6>
    <h6 class="div-dep-ticket">Owner: <%=completed.owner%></h6>
    <div class="float-right"><%=link_to "View details",view_details_path(completed)%></div>
  </div>
  <%end%>
  <% end%>
</div>


<script>
document.getElementById("defaultOpen").click();
function openList(evt, status) {
    var i, tabcontent, tablinks;

    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
    }

    tablinks = document.getElementsByClassName("tablinks");
    for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(" active", "");
    }

    document.getElementById(status).style.display = "block";
    evt.currentTarget.className += " active";
}
</script>

app/views/user_queries/new_query.html.erb
<div class="container-main">

  <div class="form-group">
  <div class="center-container">
        <%=form_for :user_query, url: add_query_path ,method: :post do |f| %>
            <div class="form-group">
              <%= f.label :Name %><br>
              <%=f.text_field(:raised_by, {:class=>'form-control'}) %>
            </div>
            <div class="form-group">
              <%= f.label :Email %><br>
              <%=f.text_field(:email, {:class=>'form-control'}) %>
            </div>

            <div class="form-group">
            <%= f.label :Department %><br>
            <select name="department" class="form-control">
                  <option id="" value="">Choose a department</option>
                  <option id="development" value="Development">Development</option>
                  <option id="marketing_service" value="Marketing services">Marketing services</option>
                  <option id="cust_service" value="Customer services">Customer services</option>
              </select>
            </div>
              <div class="form-group">
              <%= f.label :Subject %><br>
              <%=f.text_field(:subject, {:class=>'form-control'}) %>
            </div>
             <div class="form-group">
              <%= f.label :Query %><br>
               <%=f.text_area(:query, {:class=>'form-control',:rows=>'6'}) %>

            </div>
            <div class="submit-form">
              <%=f.submit "Submit", :class=>"btn btn-success"%>
            </div>
          </div>
        </div>           
        <%end%> 

  </div>
</div>

app/views/user_queries/view_details.html.erb
<div class="view">
<div class="well">
<div class="view_reply">
<h3>Ticket: <%=@user_query.ticket_id%></h3>
<h3>Raised_by: <%=@user_query.raised_by%></h3>
<h3>Replied_by: <%=@reply.replied_by%></h3>
<h4>subject: <%=@user_query.subject%></h4>
<h4>Department: <%=@user_query.department%></h4>
<h4>Status: <%=@user_query.status%></h4>
<h5> Query: <br/><%=@user_query.query%></h5>
<h5>Reply: <br/><%=@reply.reply%></h5>

<%=link_to "back",display_query_path, :class=>"btn btn-default"%>
</div>
</div></div>

app/views/user_queries/view_query.html.erb
<div class="container-view-query">
<div class="view-query float-left">
<div class="div-query-info">
<h2><%=@user_query.subject%></h2>
<h4>Raised by : <%=@user_query.raised_by%></h4>
<h4>Department : <%=@user_query.department%></h4>
<br/>
<h4>Query :</h4>
<h5><%=@user_query.query%></h5>
</div>
<div class="float-right">
<button id="reply-query" class="reply-query" onclick="ToggleReply()">Reply Now</button>
 <%= link_to '<button id="reply-onhold" class="reply-query" title="This will mark the query in ONHOLD state.">Reply Later</button>'.html_safe, onhold_status_path(@user_query) %>
<%=link_to '<button id="reply-cancel" class="reply-query">Go back</button>'.html_safe,display_query_path %>
</div>


<div class="div-reply-area">
<%=form_for :reply, url: save_reply_path,method: :post do |f| %>
<%= f.hidden_field :ticket_id, :value => @user_query.ticket_id %>
<%= f.label :reply %><br>
<%=f.text_area(:reply, {:class=>'form-control',id:'reply-box',rows:'6'}) %>
<%=f.submit "Send",:class=>"btn btn-default"%>
<%end%>
</div>
</div>


<div class="partial-div float-right">
<div class="choose-owner">
<h5>Too complicated or out of your department!! Assign this to someone else.</h5>
</div>
<div class="limit-dd">
<%=form_for :employee, url: save_owner_path,method: :post do |f| %>
 <select name="owner" class="form-control">
                <% @employee.each do|employee| %>
                  <option id=<%=employee.name%> value=<%=employee.name%>> <%=employee.name%>
                  </option>
                <%end%>
 </select>
<%= f.hidden_field :ticket_id, :value => @user_query.ticket_id %>
<%=f.submit "Assign",:class=>"btn btn-default"%>
<%end%>
</div>
</div>
</div>

<script>
	function ToggleReply()
	{
      $('.div-reply-area').toggle();
	}
</script>

app/views/user_queries/view_reply.html.erb
<div class="view">
<div class="well">
<div class="view_reply">
<h3>Ticket: <%=@user_query.ticket_id%></h3>
<h3>Raised_by: <%=@user_query.raised_by%></h3>
<h3>Replied_by: <%=@reply.replied_by%></h3>
<h4>subject: <%=@user_query.subject%></h4>
<h4>Department: <%=@user_query.department%></h4>
<h4>Status: <%=@user_query.status%></h4>
<h5> Query: <br/><%=@user_query.query%></h5>
<h5>Reply: <br/><%=@reply.reply%></h5>
</div>
</div></div>